### ISSUE TITLE
Cannot recognize MX master 3

### ISSUE THREAD

**Issue by InjecT1309** [PixlOne/logiops#102]
After the newest update logid stopped working for my MX master 3. Journalctl logs:
```
-- Reboot --
lip 19 16:05:04 askl-pc systemd[1]: Started Logitech Configuration Daemon.
lip 19 16:05:06 askl-pc logid[890]: [WARN] Error adding device /dev/hidraw1: std::exception
```

**Comment by thoastbrot** [comment]
My MX Master (1) stopped working, too - but I think, you're looking at the wrong line. In my case, hidraw0 is the receiver and why hidraw1 is reported, I don't know.

```
$ sudo /usr/bin/logid -v -c /etc/logid.cfg 
[WARN] Error adding device /dev/hidraw1: std::exception
[INFO] Detected receiver at /dev/hidraw0
[DEBUG] Unsupported device /dev/hidraw3 ignored
[DEBUG] Unsupported device /dev/hidraw4 ignored
[DEBUG] Unsupported device /dev/hidraw5 ignored
[INFO] Device Wireless Mouse MX Master not configured, using default config.
[INFO] Device found: Wireless Mouse MX Master on /dev/hidraw0:1
[DEBUG] /dev/hidraw0:1 remappable buttons:
[DEBUG] CID  | reprog? | fn key? | mouse key? | gesture support?
[DEBUG] 0x50 |         |         | YES        | 
[DEBUG] 0x51 |         |         | YES        | 
[DEBUG] 0x52 | YES     |         | YES        | 
[DEBUG] 0x53 | YES     |         | YES        | 
[DEBUG] 0x56 | YES     |         | YES        | 
[DEBUG] 0xc3 | YES     |         | YES        | 
[DEBUG] 0xc4 | YES     |         | YES        | 
```

And it's not doing anything anymore.

**Comment by thoastbrot** [comment]
Since my last install (using logiops-git from the aur) is quite ancient (commit 36ish to 152 is a lot of code), I'll try to bisect. v0.1 was working, v0.2 not.

**Comment by PixlOne** [comment]
Have you updated your config file? The device names have changed since then due to the use of the hidpp20 device name feature. Try changing `MX Master` to `Wireless Mouse MX Master` in your config file.

**Comment by InjecT1309** [comment]
Changed from MX Master 3000 to Wireless Mouse MX Master, did not help.

**Comment by PixlOne** [comment]
That's odd, can you post the log output now?

**Comment by thoastbrot** [comment]
[INFO] Device found: Wireless Mouse MX Master on /dev/hidraw0:1

Didn't see that as device name, but as description... That's it, thank you!

@InjecT1309 check that Text, it's probably different for your model.

**Comment by InjecT1309** [comment]
Its the same as before:
```
lip 19 21:05:46 askl-pc systemd[1]: Stopping Logitech Configuration Daemon...
lip 19 21:05:46 askl-pc systemd[1]: logid.service: Succeeded.
lip 19 21:05:46 askl-pc systemd[1]: Stopped Logitech Configuration Daemon.
lip 19 21:05:46 askl-pc systemd[1]: Started Logitech Configuration Daemon.
lip 19 21:05:48 askl-pc logid[10116]: [WARN] Error adding device /dev/hidraw1: std::exception
```

**Comment by thoastbrot** [comment]
@InjecT1309 you need to run it in the shell with -v to get that information.

**Comment by InjecT1309** [comment]
Ok, this fixes my issue, the device name was 'Wireless Mouse MX Master 3' (with a 3 at the end)
