### ISSUE TITLE
No config change, but now I get a FileIOException

### ISSUE THREAD

**Issue by Qwerty-Space** [PixlOne/logiops#103]
I have tried with the logiops-git and logiops AUR packages
```
[ERROR] I/O Error while reading ~/.config/logiops/logid.cfg: FileIOException
[INFO] Device Wireless Mouse MX Master 2S not configured, using default config.
[INFO] Device found: Wireless Mouse MX Master 2S on /dev/hidraw5:1
```

[config](https://del.dog/ywiwestucr.txt)

---

[Solution](https://github.com/PixlOne/logiops/issues/103#issuecomment-661241318)

>Change name: "MX Master 2S"; to name: "Wireless Mouse MX Master 2S";

**Comment by PixlOne** [comment]
Are you sure the file is in that path? Can you post the full output and the command you used to run it?

**Comment by Qwerty-Space** [comment]
> Are you sure the file is in that path? Can you post the full output and the command you used to run it?

Thanks for the fast reply
It definitely is there

![image](https://user-images.githubusercontent.com/6967592/87968861-fb789b80-cab8-11ea-9711-c38263e76543.png)

**Comment by PixlOne** [comment]
hmm it seems to be reading that file just fine

**Comment by Qwerty-Space** [comment]
It has for some reason stopped saying there's a FileIOException, but it says it's not configured

**Comment by PixlOne** [comment]
Change `name: "MX Master 2S";` to `name: "Wireless Mouse MX Master 2S";`

**Comment by Qwerty-Space** [comment]
Yeah that worked
I wonder why it was working before then?

**Comment by PixlOne** [comment]
The latest update changed how names work in some cases.

**Comment by Qwerty-Space** [comment]
Ah I see

**Comment by Qwerty-Space** [comment]
After a restart it's happening again

![image](https://user-images.githubusercontent.com/6967592/87994410-bec29980-cae4-11ea-86e8-e5c1c76636e0.png)

**Comment by PixlOne** [comment]
You can fix this by either using the full path (i.e. substitute `~` for `/home/<user>`) or removing the quotation marks.

When you run a command with the file path in quotation marks, the shell will ignore special characters like `~`. For example, if you try `ls "~"`, ls will respond by saying `ls: cannot access '~': No such file or directory`; if you run `ls ~`, it will read the path as your home folder and properly list the files in your home directory.

**Comment by Qwerty-Space** [comment]
Oh I didn't know that, thank you
