### ISSUE TITLE
MxMaster 2s or 3 support?

### ISSUE THREAD

**Issue by GitJamz** [PixlOne/logiops#18]
Did anyone try logiops with mxmaster 2 or 3 ?

**Comment by wiebel** [comment]
Sure, works perfectly wirh my MX Master 3.

**Comment by GXGOW** [comment]
I'm also using logiops with the MX Master 3. Works like a charm!

**Comment by adrfantini** [comment]
Can you map the thumb button with this tool, or is it still hardcoded with Ctrl+Alt+Tab?

**Comment by GXGOW** [comment]
Sure, you can map cid's 0x53 (back button) and 0x56 (forward button) in your `logid.cfg` like this:

```
        {
            cid: 0x53;
            action =
            {
                type :  "Keypress";
                keys: ["KEY_LEFTCTRL", "KEY_PAGEUP"];
            };
        },
        {
            cid: 0x56;
            action =
            {
                type :  "Keypress";
                keys: ["KEY_LEFTCTRL", "KEY_PAGEDOWN"];
            };
        }
```

**Comment by adrfantini** [comment]
> Sure, you can map cid's 0x53 (back button) and 0x56 (forward button) in your `logid.cfg` like this:
> 
> ```
>         {
>             cid: 0x53;
>             action =
>             {
>                 type :  "Keypress";
>                 keys: ["KEY_LEFTCTRL", "KEY_PAGEUP"];
>             };
>         },
>         {
>             cid: 0x56;
>             action =
>             {
>                 type :  "Keypress";
>                 keys: ["KEY_LEFTCTRL", "KEY_PAGEDOWN"];
>             };
>         }
> ```

Thanks, but I meant the lower button where the thumb rests (which by default does Ctrl+Alt+Tab), not the two small buttons that are forward/back by default.

**Comment by GXGOW** [comment]
> Thanks, but I meant the lower button where the thumb rests (which by default does Ctrl+Alt+Tab), not the two small buttons that are forward/back by default.
> 
> (edit: MXM3)

Oh, my mistake. I think you can set it the same way with cid `0xc3`. All other control IDs [are listed on the wiki](https://github.com/PixlOne/logiops/wiki/CIDs) by the way.

**Comment by adrfantini** [comment]
That's awesome, it works flawlessly. Thanks!

**Comment by Fourstepper** [comment]
Sorry to hijack, is it possible to make the thumb button + mouse movement change workspaces in GNOME/KDE, or still not possible?

Thank you!

**Comment by GXGOW** [comment]
> Sorry to hijack, is it possible to make the thumb button + mouse movement change workspaces in GNOME/KDE, or still not possible?
> 
> Thank you!

That is possible, I have it configured for the up/down gestures like this for GNOME:

```
    buttons: (
        {
            cid: 0xc3;
            action =
            {
                type: "Gestures";
                gestures: (
                    {
                        direction: "Up";
                        mode: "OnRelease";
                        action =
                        {
                            type: "Keypress";
                            keys: ["KEY_LEFTMETA", "KEY_PAGEUP"];
                        };
                    },
                    {
                        direction: "Down";
                        mode: "OnRelease";
                        action =
                        {
                            type: "Keypress";
                            keys: ["KEY_LEFTMETA", "KEY_PAGEDOWN"];
                        };
                    }
                );
            };
        },
   );

**Comment by jef** [comment]
> I'm also using logiops with the MX Master 3. Works like a charm!

**Comment by vthuongt** [comment]
The MX Master 2S works for me with Ubuntu 18.04 and following config:

```
devices: (
{
    name: "MX Master 2S";
    smartshift:
    {
        on: false;
        threshold: 15; # 7 is ideal for work
    };
    hiresscroll:
    {
        hires: false;
        invert: false;
        target: false;
    };
    dpi: 800;

    buttons: (
        {
            cid: 0xc3;
            action =
            {
                type: "Gestures";
                gestures: (
                    {
                        direction: "Up";
                        mode: "OnRelease";
                        action =
                        {
                            type: "Keypress";
                            keys: ["KEY_LEFTCTRL", "KEY_LEFTALT",  "KEY_UP"];
                        };
                    },
                    {
                        direction: "Down";
                        mode: "OnRelease";
                        action =
                        {
                            type: "Keypress";
                            keys: ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_DOWN"];
                        };
                    },
                    {
                        direction: "Left";
                        mode: "OnRelease";
                        action =
                        {
                            type: "Keypress";
                            keys: ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_LEFT"];
                        };
                    },
                    {
                        direction: "Right";
                        mode: "OnRelease";
                        action =
                        {
                            type: "Keypress";
                            keys: ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_RIGHT"];
                        }
                    },

                    {
                        direction: "None"
                        mode: "OnRelease";
                        action =
                        {
                            type: "Keypress";
                            keys: ["KEY_LEFTMETA"];
                        }
                    }
                );
            };
        },
        {
            cid: 0xc4;
            action =
            {
                type = "ToggleSmartshift";
            };
        }
    );
}
);
```
I can use gestures to switch workspaces in gnome and a single tap on the thumb button shows the overview for open windows (like pressing Win/Alt key).

**Comment by jef** [comment]
I will say that it works just fine, but the main problem is that if and when it loses connection, I have to restart the `logid.service`. Not sure if it's just me or a side effect as of now.

**Comment by tomekand11** [comment]
@jef does it happen on bluetooth only ?

**Comment by jef** [comment]
> @jef does it happen on bluetooth only ?

I was using the dongle. That being said, I built from latest master a month or so after and didn't have any problems. I no longer have the mouse, but it seemed to be working fine then!

**Comment by cerealfordinner** [comment]
Does anyone know how I would bind the thumb button to control + v (paste) to mimic how I use it Windows? Thank you in advance.

**Comment by jef** [comment]
> Does anyone know how I would bind the thumb button to control + v (paste) to mimic how I use it Windows? Thank you in advance.

Off topic, but:

https://github.com/PixlOne/logiops/wiki/CIDs

Control ID | Function
-- | --
0x0052 | Middle Mouse Button

```
buttons: (
        {
            cid: 0x0052;
            action =
            {
                type :  "Keypress";
                keys: ["KEY_LEFTCTRL", "KEY_V"];
            };
        }
    );
```

**Comment by cerealfordinner** [comment]
> > Does anyone know how I would bind the thumb button to control + v (paste) to mimic how I use it Windows? Thank you in advance.
> 
> Off topic, but:
> 
> https://github.com/PixlOne/logiops/wiki/CIDs
> 
> Control ID	Function
> 0x0052	Middle Mouse Button
> ```
> buttons: (
>         {
>             cid: 0x0052;
>             action =
>             {
>                 type :  "Keypress";
>                 keys: ["KEY_LEFTCTRL", "KEY_V"];
>             };
>         }
>     );
> ```

Would this work for the thumb button on the side of the MX Master 2S?

whenever I run ```xev``` and capture the input it doesn't show as a button press which is what's messing me up with the binding.

```
KeyRelease event, serial 38, synthetic NO, window 0x3a00001,
    root 0x1de, subw 0x3a00002, time 25323386, (55,22), root:(2072,179),
    state 0x1c, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 38, synthetic NO, window 0x3a00001,
    root 0x1de, subw 0x3a00002, time 25323396, (55,22), root:(2072,179),
    state 0x14, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by jef** [comment]
Your middle mouse button is probably a different CID. Could be `0x1de`. Not really sure how to read that output.

But once you find your correct CID, the rest should be fine.

**Comment by adrian-huminiuc** [comment]
I wanted to bind the top button, (button behind the wheel ) to act as the middle button.
If it helps anyone here is the config, works with Wireless Mouse MX Master 3, ubuntu 22
```echo 'devices: (
{
    name: "Wireless Mouse MX Master 3";
    smartshift:
    {
        on: true;
        threshold: 10;
    };
    hiresscroll:
    {
        hires: true;
        invert: false;
        target: false;
    };
    dpi: 1000;

    buttons: (
       // mouse wheel click (old middle button) will toggle the smoothness of the scrolling
        {
            cid: 0x52;
            action =
            {
                type: "ToggleSmartShift";
            };
        },
        //top button (which toggled the smoothness of the scrolling) is now the middle button (like: closing tabs, copy pasta, etc)
        {
            cid: 0xc4;
            action =
            {
                type: "Keypress";
                keys: ["BTN_MIDDLE"];
            };
        }
    );
}
);' | sudo tee /etc/logid.cfg

**Comment by PixlOne** [comment]
Closing this issue as these mice are supported.
