### ISSUE TITLE
Linux "windows" (super) button code

### ISSUE THREAD

**Issue by Piranit** [PixlOne/logiops#201]
Hello!
I wanted to assign a "windows" (super) button to the gesture button on ubuntu 20.04.
Please tell me which code of the button?
Thanks!

**Comment by hasimsait** [comment]
KEY_LEFTMETA. Read the wiki. "For a list of key/button strings, refer to linux/input-event-codes.h." https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

**Comment by olehyaremko** [comment]
@hasimsait thank you so much!
I saw this document.
I was looking for a button with names like "Super", "Windows" or "Special".
Nowhere did I find information that this button is called "Meta".
There was no comment for "KEY_LEFTMETA" in that document.
Now I will know, have a nice day!

**Comment by Piranit** [comment]
@hasimsait thank you so much!
I saw this document.
I was looking for a button with names like "Super", "Windows" or "Special".
Nowhere did I find information that this button is called "Meta".
There was no comment for "KEY_LEFTMETA" in that document.
Now I will know, have a nice day!

**Comment by dieggsy** [comment]
To add a bit to the confusion, Alt is sometimes called meta. Good this is at least documented in an issue though.

**Comment by ElectricRCAircraftGuy** [comment]
@hasimsait , is it documented anywhere that "meta" means the <kbd>Super</kbd> or <kbd>Windows</kbd> key? Or, did you just identify this by guessing and/or trial and error while looking in the `input-event-codes.h` file?
