### ISSUE TITLE
Could Not Display "logid"

### ISSUE THREAD

**Issue by Yael50** [PixlOne/logiops#203]
Kind of doing this for the first time and I don't really understand what the problem is. Maybe someone can help.
I built everything and installed logiops. However when I want to open it it say "Could not display 'logid', There is no application installed for "shared library" files."
Anyone have an idea what might solve the problem?

**Comment by tomekand1** [comment]
This app does not have an graphical interface, all the settings are set via config "etc/logid.cfg" (Ubuntu) u can edit that file in order to apply your new configuration

**Comment by maxikd** [comment]
Adding to @tomekand1's answer, you have to run logid from the terminal
