### ISSUE TITLE
Time out on default device

### ISSUE THREAD

**Issue by andreiDamoc** [PixlOne/logiops#21]
Hi, do you have any idea what I do wrong? 
I try to make it work on ubuntu 18.04

`[INFO] Found Logitech USB Receiver on /dev/hidraw0 

[INFO] MX Master detected: device 1 on /dev/hidraw0

[ERROR] Time out on default device: /dev/hidraw1 (possibly asleep)`

**Comment by PixlOne** [comment]
Unless there's an actual issue, timeout messages can generally be ignored.

Although, I don't really know why a receiver would have a timeout error, usually it's the wireless devices.

**Comment by de-es** [comment]
Everything is working fine (MX Master 3), but is there a way to suppress the time out error message every 10 seconds spaming the log? Thanks in advance.
