### ISSUE TITLE
Is there a way to use this with sysvinit instead of systemd?

### ISSUE THREAD

**Issue by Pistrie** [PixlOne/logiops#237]
I'm using MX Linux without systemd, so I am not able to use the systemd service.

**Comment by NeroDoD** [comment]
You need to write a sysvinit script equivalent to the provided systemd service. I've never used sysvinit but in case it is helpful, here's an OpenRC script I wrote to use logiops on Gentoo. You might even be able to find some tools on the internet to convert systemd services to sysvinit but it shouldn't be too hard anyway.


```
#!/usr/bin/openrc-run

name=$RC_SVCNAME
description="Logitech Configuration Daemon"
supervisor="supervise-daemon"
command="/usr/bin/logid"
command_args=""
command_user="root"

reload() {
	ebegin "Reloading $RC_SVCNAME"
	/bin/kill -HUP $MAINPID
	eend $?
}
```
