### ISSUE TITLE
Undefined symbol when running logid -v

### ISSUE THREAD

**Issue by Guara92** [PixlOne/logiops#24]
Hi @PixlOne,

I installed logiops and all the dependencies, on ubuntu 19.10, including libhidpp, making a symlink /usr/local/lib/libhidpp.so to /usr/lib/libhidpp.so.
When i run logid -v this error is returned:
logid: symbol lookup error: logid: undefined symbol: _ZN7HIDPP109IReceiver6EventsE

What I'm missing?

**Comment by Guara92** [comment]
I see now that libhidpp is a submodule of this project, I have not cloned the submodule and when logid did not start due to the lack of libhidpp, I installed it from its repository. Could this possibly create the problem?

**Comment by PixlOne** [comment]
Did you use my fork of libhidpp? The original libhidpp repository is missing some features (e.g. the IReceiver feature which you're missing the symbol for).

**Comment by Guara92** [comment]
no i used the original repo. I see in the CMakeLists.txt that the submodule should be fetched if missing but this has not happened.
If i try to init the submodule i have an error: 
>git submodule update --init -- hidpp
error: pathspec 'hidpp' did not match any file(s) known to git

**Comment by PixlOne** [comment]
I'm not too sure why you're having that issue, but you manually clone this repo: https://github.com/PixlOne/hidpp

**Comment by Guara92** [comment]
Thanks for the support, with your repo is working fine.
