### ISSUE TITLE
Could I use the MX Master Mouse to emulate keyboard input "DEL", "ESC", or "F2" to enter BIOS when computer boot?

### ISSUE THREAD

**Issue by dalao3** [PixlOne/logiops#242]
I'm now using a bluetooth keyboard so I can't enter BIOS when computer boot up by pressing "DEL", "ESC", or "F2" keys.
I'm thinking about whether the keys on the MX Master Mouse is able to work like a keyboard. When computer boot up, I can press the buttons on the mouse to enter BIOS?
If yes, how to configure it?

**Comment by PixlOne** [comment]
No, logiops remaps buttons by listening for button press/release events and then using a virtual input device to send it to the OS. As far as I know, on most Logitech devices (including the MX Master), there is no way to remap the buttons on the mice without having a daemon do something similar to this. This could be different on some gaming mice that have persistent button mapping, but I don't really know.
