### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by fourstepper** [PixlOne/logiops#252]
I have made a room on Matrix with the name logiops (at #logiops:matrix.org)

I think this could be a good community place for people to find each other? Or is there one established?

Thanks!

**Comment by PixlOne** [comment]
We don't really have an established chat, but if people do want to join and discuss this project, I guess we could use this.

**Comment by fourstepper** [comment]
For now I will be holding the room - if there is need for transfer, I will let it go to anyone from the project :)
