### ISSUE TITLE
OnFewPixels seems to only work once

### ISSUE THREAD

**Issue by muesli** [PixlOne/logiops#29]
I'm trying to hook up my thumb button to react to directional moves while pressed, like in the example configuration. That works fine, but when I try to switch from `OnRelease` mode to `OnFewPixels` the action seems to only ever be triggered once, until the next restart of `logid`.

**Comment by PixlOne** [comment]
That's weird, my MX Master doesn't seem to have that issue.

Could you post a log of the program and your config file?

**Comment by muesli** [comment]
Config:

```
devices: (
{
    name: "MX Master 3";
    smartshift:
    {
        on: true;
        threshold: 10;
    };
    hiresscroll:
    {
        hires: false;
        invert: false;
        target: false;
    };
    dpi: 1250;

    buttons: (
        {
            cid: 0xc3;
            action =
            {
                type: "Gestures";
                gestures: (
                    {
                        direction: "Up";
                        mode: "OnFewPixels";
                        action =
                        {
                            type: "Keypress";
                            keys: ["KEY_PAUSE"];
                        };
                    },
                    {
                        direction: "Down";
                        mode: "OnRelease";
                        action =
                        {
                            type: "Keypress";
                            keys: ["KEY_F12"];
                        };
                    },
                    {
                        direction: "None";
                        mode: "OnRelease";
                        action =
                        {
                            type: "Keypress";   
                            keys: ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_TAB"];
                        };
                    }
                );
            };
        }
    );
}
);
```

`KEY_PAUSE` triggers my Terminal being focused on my system. When I hold the thumb button and move the mouse up the terminal quickly gains focus, then loses it again. It looks as if the event is triggered twice in very quick succession - and then never again. The other actions keep working.

**Comment by PixlOne** [comment]
Your config file was missing a `pixels` field for OnFewPixels which resulted in undefined behaviour. It should have warned you about that and disabled the gesture but for some reason, it didn't.

I just fixed this in the latest commit.

**Comment by muesli** [comment]
@PixlOne Oh, I see. Thank you! I also misunderstood the function: I thought it'd only trigger once (after a "few" pixels). Maybe such a "single-shot" method could be added as well?

**Comment by PixlOne** [comment]
Yeah, I didn't really know what I should call it. In hindsight, I should have called it "PixelInterval". I might change it but I'd like to avoid messing with people's configs.

**Comment by muesli** [comment]
I agree, the config should probably remain compatible. We could either add a separate `singleshot` mode, or switch to that behavior in `OnFewPixels` mode when `pixels` is set to 0?

**Comment by muesli** [comment]
Also, maybe it would be a nice idea to add a `OnFewPixels` mode configuration to the example configuration file?
