### ISSUE TITLE
Gnome 42 gesture support... MX 3s

### ISSUE THREAD

**Issue by ashupednekar** [PixlOne/logiops#337]
![image](https://user-images.githubusercontent.com/25405037/197371933-3edf5e79-023c-4022-90b2-66f3177c9f58.png)

**Comment by ashupednekar** [comment]
how to get this configured? pls help

**Comment by chermnyx** [comment]
It's not currently supported https://github.com/PixlOne/logiops/issues/268

**Comment by PixlOne** [comment]
Closing as duplicate
