### ISSUE TITLE
Will this project still be necessary after Kernel 6.1?

### ISSUE THREAD

**Issue by johnhamelink** [PixlOne/logiops#347]
Hi there,

I'm reading that Linux Kernel 6.1 includes fixes to HID++ Logitech mice. I was wondering to what extent these changes overlap with Logiops and whether there might be issues upgrading? I'm an MX Master 2S user.

https://www.phoronix.com/news/Linux-61-Logitech-Hi-Res-Scroll

**Comment by PixlOne** [comment]
This project is still necessary as the previous commenter said, there's plenty of configuration options that cannot be provided in the kernel driver.
