### ISSUE TITLE
Make Command Failing

### ISSUE THREAD

**Issue by calcelli** [PixlOne/logiops#367]
I am receiving the errors
`../logiops/src/logid/./config/types.h:354:50: error: class template argument deduction failed:
  354 |         struct config_io<map<K, V, KeyName, Cmp, Alloc>> {
`

`logiops/src/logid/./config/types.h:354:50: error: no matching function for call to ‘string_literal(string_literal<...auto...>)’`

`logiops/src/logid/./config/map.h:29:19: note: candidate: ‘template<long unsigned int N> string_literal(const char (&)[N])-> logid::config::string_literal<N>’
   29 |         constexpr string_literal(const char (& str)[N]) {
`

Amongst many others when I am following the compile instructions in the ReadME.

I am sorry if this is a duplicate or the wrong place to ask. I tried looking through open issues and could not find it

System is running Ubuntu 20.04.6 LTS

**Comment by PixlOne** [comment]
So I've just tried building on Ubuntu 20.04, turns out it still uses GCC 9 which doesn't have full C++20 support. I found some other compile issues on GCC 10 which I'll fix soon. In any case, I'll update dependencies and figure out how to put a better warning for this.

**Comment by calcelli** [comment]
Okay Cool, So it should work on 22?

**Comment by PixlOne** [comment]
Should now work on 22 or by upgrading g++ to version 10, I'll try fixing the errors to get it working on g++ 9
