### ISSUE TITLE
Unable to upgrade to v3 -- missing dependency libipcgull.so

### ISSUE THREAD

**Issue by sqrt-7** [PixlOne/logiops#372]
trying to upgrade on opensuse tumbleweed
```Problem: nothing provides 'libipcgull.so()(64bit)' needed by the to be installed logiops-0.3.1-4.1.x86_64```

Tried to compile it from source ( github.com/PixlOne/ipcgull ) but I'm too dumb, some step-by-step help would be appreciated.

**Comment by PixlOne** [comment]
The library is statically linked, so it is not provided.

This is an issue with the package you're using, I'm not sure who maintains it on OpenSUSE but you should file a bug report with them.

In the meantime, until they fix it, you can follow the build instructions in the README for this repository.
