### ISSUE TITLE
/etc/logid.cfg not found

### ISSUE THREAD

**Issue by tirefrier** [PixlOne/logiops#41]
----- $systemctl status logid --------
● logid.service - Logitech Configuration Daemon
     Loaded: loaded (/usr/lib/systemd/system/logid.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2020-04-10 10:13:27 CDT; 3s ago
   Main PID: 4447 (logid)
      Tasks: 3 (limit: 38408)
     Memory: 1.4M
     CGroup: /system.slice/logid.service
             └─4447 /usr/bin/logid

Apr 10 10:13:27 helios systemd[1]: Started Logitech Configuration Daemon.
Apr 10 10:13:27 helios logid[4447]: **[WARN] No button configuration found, reverting to null config.**

-------- $ ls /etc/ | grep logi -----------
logid.cfg
login.defs

**Comment by PixlOne** [comment]
It appears to find the configuration file but it can't find any button mappings in the configuration for your device.

Do you have a buttons field in your configuration for the device?

Check out a sample config here: https://github.com/PixlOne/logiops/blob/master/logid.example.cfg

Also, be sure to check out [the wiki page on how to configure the device](https://github.com/PixlOne/logiops/wiki/Configuration)

**Comment by tirefrier** [comment]
I do have a buttons field in my .cfg, I actually believe I am using your sample with only a few minor changes. I'll attach it below, I had to change the extension for it to allow me to upload it, but it is /etc/logid.cfg on my system.

[logid.cfg.txt](https://github.com/PixlOne/logiops/files/4463628/logid.cfg.txt)

**Comment by PixlOne** [comment]
The error message is referring to "Other Logitech USB Receiver".

I'll try to remove the error message (in case a device doesn't support ReprogControls) and include line numbers/device names for the error messages.

The configuration on the MX Master 3 seems to be fine so I'll close the issue for now.
