### ISSUE TITLE
Scrolling speed becomes super slow with logid active

### ISSUE THREAD

**Issue by muesli** [PixlOne/logiops#43]
Since a recent update scrolling with the wheel is unusably slow, as soon as logid is running. Stopping the process alone doesn't work either, I actually need to turn my mouse off and on again to make it scroll normally again, too.

Using an MX Master 3.

**Comment by PixlOne** [comment]
This is likely something to do with how Linux 5.6 introduced MX Master 3 support to the hid-logitech-hidpp module.

Try enabling hires scrolling, that should allow your scrolling to properly adjust to the new module.

**Comment by muesli** [comment]
Oh, that actually makes a lot of sense! I probably updated both at the same time! Testing later tonight.

**Comment by muesli** [comment]
Works fine as soon as I've enabled `hires`, indeed! Thank you!
