### ISSUE TITLE
Logitech MX Master 3S not reconized

### ISSUE THREAD

**Issue by jacksonbaxter** [PixlOne/logiops#437]
I have my Logitech MX Master 3S connected to my computer via the Bolt Receiver. When I run logid -v I only get this with no connected device.

```
$ sudo logid -v
[DEBUG] Unsupported device /dev/hidraw7 ignored
[DEBUG] Unsupported device /dev/hidraw3 ignored
[DEBUG] Unsupported device /dev/hidraw4 ignored
[DEBUG] Unsupported device /dev/hidraw5 ignored
[INFO] Detected receiver at /dev/hidraw6
[DEBUG] Unsupported device /dev/hidraw0 ignored
[DEBUG] Unsupported device /dev/hidraw1 ignored
[DEBUG] Unsupported device /dev/hidraw2 ignored
```

Does anyone have a solution to this?

**Comment by MSiteDev** [comment]
Same output, and config not works at all
$ sudo logid -v
[sudo] password for mariusz: 
[DEBUG] Unsupported device /dev/hidraw1 ignored
[DEBUG] Unsupported device /dev/hidraw2 ignored
[DEBUG] Unsupported device /dev/hidraw3 ignored
[INFO] Detected receiver at /dev/hidraw4
[DEBUG] Unsupported device /dev/hidraw5 ignored
[DEBUG] Unsupported device /dev/hidraw6 ignored
[DEBUG] Unsupported device /dev/hidraw0 ignored

$ sudo systemctl status logid.service
● logid.service - Logitech Configuration Daemon
     Loaded: loaded (/lib/systemd/system/logid.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-02-19 22:04:01 CET; 5min ago
   Main PID: 2647 (logid)
      Tasks: 8 (limit: 37710)
     Memory: 4.9M
        CPU: 31ms
     CGroup: /system.slice/logid.service
             └─2647 /usr/local/bin/logid

lut 19 22:04:01 mariusz-laptop systemd[1]: Started Logitech Configuration Daemon.
lut 19 22:04:01 mariusz-laptop logid[2647]: [INFO] Detected receiver at /dev/hidraw4
lut 19 22:07:49 mariusz-laptop logid[2647]: [INFO] Device found: MX Master 3S on /dev/hidraw4:2
lut 19 22:08:05 mariusz-laptop logid[2647]: [INFO] /dev/hidraw4:2 fell asleep.
lut 19 22:08:22 mariusz-laptop logid[2647]: [WARN] Failed to add device /dev/hidraw7 after 5 tries. Treating as failure.
lut 19 22:08:22 mariusz-laptop logid[2647]: [WARN] Failed to add device /dev/hidraw7 after 5 tries. Treating as failure.
lut 19 22:09:59 mariusz-laptop logid[2647]: [INFO] /dev/hidraw4:2 woke up.

**Comment by kstoykov** [comment]
It seems that 3S is supported only via bluetooth at the moment.

**Comment by kstoykov** [comment]
I cannot make mine to work using logi bolt as well

**Comment by forresthopkinsa** [comment]
I was having this problem when running the compiled binary directly; when I installed it, the problem went away

**Comment by pasanflo** [comment]
Hi! I was troubleshooting with this problem aswell, I managed to fix it by:

1. Compiling the binaries. (I'm working on a Manjaro Linux, but some people recommended to build the binaries by ourselves)
2. Fixing the device configuration name to "MX Master 3S" on /etc/logid.cfg
3. `sudo logid --config abcdefg` (set the config an unexisting one to force logid to read the default one at /etc/logid.cfg)
4. `systemctl restart logid` Restart the daemon

And then it was working as expected. Had to change a couple of default settings to fix high resolution scrolling but I'm happy with having fixed in my machine.

**Comment by Geckuss** [comment]
> Hi! I was troubleshooting with this problem aswell, I managed to fix it by:
> 
> 1. Compiling the binaries. (I'm working on a Manjaro Linux, but some people recommended building the binaries)
> 2. Copying the [default configuration](https://github.com/PixlOne/logiops/blob/main/logid.example.cfg) on the default config file at /etc/logid.cfg
> 3. Fixing the device configuration name to "MX Master 3S" on /etc/logid.cfg [Link to my logid.cfg](https://gist.github.com/pasanflo/c7d745b42ad4ad8ba8cedd88654a8865)
> 4. `sudo logid --config abcdefg` (set the config an unexisting one to force logid to read the default one at /etc/logid.cfg)
> 5. `systemctl restart logid` Restart the daemon
> 
> And now checking with status we see the mouse.
> 
> ![image](https://private-user-images.githubusercontent.com/3006784/309816357-c10c7079-24da-4502-9fba-af8ad5a44042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTIxNDcsIm5iZiI6MTcwOTg1MTg0NywicGF0aCI6Ii8zMDA2Nzg0LzMwOTgxNjM1Ny1jMTBjNzA3OS0yNGRhLTQ1MDItOWZiYS1hZjhhZDVhNDQwNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMjI1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ2Mjg0N2NjZjc5YzYzNzlmNmM5MDcwM2Y3NmQxNmJiMTIyMzkwNjlhZjQ0ZTUzZTVmM2FmYjdlMTc4OGZhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EQMaUXVIf_fQWrwKH6q8k6Y64ekcppA_Q_lUjXJqVdg)
> 
> And then it was working as expected. Had to change a couple of default settings to fix high resolution scrolling but I'm happy with having it fixed on my machine.
> 
> Kudos to Michael Verschoof on his amazing [post on Medium](https://michael-verschoof.medium.com/setting-up-mx-master-mouse-on-linux-aae0e2ce3962) about this specific problem.

Thank you for making clear steps. I am using Ubuntu, and I installed logiops by compiling source code, and then followed your steps. However, logiops detects only receiver, not my mouse. Any idea what to troubleshoot?
