### ISSUE TITLE
Can't find logid.cfg

### ISSUE THREAD

**Issue by dinirichard** [PixlOne/logiops#45]
----- $ sudo systemctl status logid --------

● logid.service - Logitech Configuration Daemon
   Loaded: loaded (/lib/systemd/system/logid.service; enabled; vendor preset: en
   Active: active (running) since Tue 2020-04-14 09:06:08 EEST; 1min 33s ago
 Main PID: 7117 (logid)
    Tasks: 10 (limit: 4915)
   CGroup: /system.slice/logid.service
           └─7117 /usr/local/bin/logid

Apr 14 09:06:08 dini-lnx systemd[1]: Started Logitech Configuration Daemon.
Apr 14 09:06:08 dini-lnx logid[7117]: [ERROR] I/O Error while reading /etc/logid

-------- $ ls /etc/ | grep logi -----------
login.defs

**Comment by PixlOne** [comment]
You need to create /etc/logid.cfg, read the logid.example.cfg file in the repo and the Configuration section of the wiki for more details on how to configure logid.
