### ISSUE TITLE
Compiler Error: »transform« is not element of »std«

### ISSUE THREAD

**Issue by Sebastian0100** [PixlOne/logiops#451]
During compilation the error »transform« is not element of »std« happens at logiops/src/logid/./config/group.h:151:18. The cause for this seems to be that the header file does not include the Algorithms library, as including it resolves the problem.

Although since nobody else seems to have encountered this issue, this might be related to my specific environment.

**Comment by Sniptzler** [comment]
I encountered the same Error but the fix worked seamingless.

**Comment by debbinkm** [comment]
I also just ran into this. Adding `#include <algorithm>` to group.h does indeed allow the project to compile, as @Sebastian0100 mentioned. Not sure why this is all of the sudden an issue, though.

**Comment by kada49** [comment]
Maybe we all are using a new version of the compiler which changes some includes, no idea

**Comment by BrainFreezy** [comment]
thank you that worked for me aswell

**Comment by PixlOne** [comment]
Should be fixed with the recent PR.
