### ISSUE TITLE
KEY for SUPER

### ISSUE THREAD

**Issue by FilipeGood** [PixlOne/logiops#46]
Hi, 
First, let me say thanks for the great software that you developed :)

I have the Mx Master 3, and I can't find with is the keypress button for the SUPER key
I know this isn't really an issue but can someone tell me?
Thanks

**Comment by PixlOne** [comment]
It's KEY_LEFTMETA for the left super key and KEY_RIGHTMETA for the right super key.

[You can refer to linux/event-codes.h to get a full list of key codes.](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h)
