### ISSUE TITLE
Interprocess communication for handling configurations

### ISSUE THREAD

**Issue by rockerbacon** [PixlOne/logiops#5]
Currently there's a functional service but no way to communicate with it, if one wishes to change configurations it is necessary to edit "/etc/logid.cfg" and restart logid.

My suggestion is implementing a minimalistic POSIX socket communication system where an external tool can tell logid to use a file in a specific path as a new configuration. This would allow said to tool to quickly change profiles so that things such as application specific profiles would be possible.

Allowing logid to read from a location other than /etc also has the added benefit of tools not needing root privileges to change configurations.

**Comment by PixlOne** [comment]
Damn you read my mind, I was literally just in the process of typing this issue out.

After some final refactoring and possible bug fixes in logid, I'm planning to create a logid socket to allow logictl to control the daemon.
