### ISSUE TITLE
Documentation: Mention somewhere that it's possible to add gestures for any and all keys

### ISSUE THREAD

**Issue by Elijas** [PixlOne/logiops#52]
Official Logitech software allows for gestures only for Thumb key, while this driver allows to have gestures for all keys which is amazing (this makes the MX Master 3 to effectively have ~30 buttons). I didn't realize this immediately, since I assumed this driver to only be a subset of official functionality.

I think we could have footnote in README.md that mentions this

https://gist.github.com/Elijas/563dd13c3b7492bdb43e3aa8e861f844

**Comment by PixlOne** [comment]
I've added this to the wiki.
