### ISSUE TITLE
Unable to detect config file (/etc/logid.cfg)

### ISSUE THREAD

**Issue by jackhhchan** [PixlOne/logiops#63]
Hi,

I have set up the /etc/logid.cfg file and set the value of 'name' to "MX Master 3" as shown by starting logid.

However, it seems /etc/logid.cfg isn't detected. 

Note: I ran logid when it was freshly installed and /etc/logid.id is detected and run as expected. It then stopped detecting the file suddenly and haven't since.

I have tried:
- specifically setting path to /etc/logid.cfg using -c option.
- reinstalling logiops
- restarting the computer

![image](https://user-images.githubusercontent.com/34367064/82282693-d0e66580-99d7-11ea-81c7-4cf8c96257ac.png)

Also, what's the [input-event-code](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h) for the default thumb button to show windows? (i.e. ctrl-alt-down arrow for linux mint)

Thanks heaps!

UPDATE #1 
--- 
the config file here:
```
devices: (
{
    name: "MX Master 3";
    smartshift:
    {
        on: true;
        threshold: 60;
    };
    hiresscroll:
    {
        hires: true;
        invert: false;
        target: false;
    };
    dpi: 1200;

    buttons: (
        {
            cid: 0xc3;
            action =
            {
                type: "Keypress"
                keys: ["BTN_LEFT"]
            };
        },
        {
            cid: 0xc4;
            action = "ToggleSmartShift";
        }
    );
}
); 
```

**Comment by PixlOne** [comment]
Can you post your config file?

Also, I'm not quite sure what you mean by default thumb button, do you mean how to do Ctrl, alt, Down arrow? In that case just set the keys to `["KEY_LEFTCTRL", "KEY_LEFTALT", 'KEY_DOWN"]`.

**Comment by ElijahLynn** [comment]
I am having this same issue after a default install of https://aur.archlinux.org/packages/logiops-git/ that installed a default /etc/logid.cfg file. I'll post back once I get it working. Maybe my /etc/logid.cfg was from a previous attempt as I did have Logiops installed a year ago trying to get a Logitech touchpad installed.

**Comment by ElijahLynn** [comment]
K, got the file loading now, it always was loading but somehow the file laid down on /etc/logid.cfg had the name `"MX Master"` and needed to be `"MX Master 3"` for it to get picked up. Also worth noting is that when I do a `systemctl reload logid` the changes still took about 2-5 seconds to get picked up after the reload finished.
