### ISSUE TITLE
Problems with hires setting

### ISSUE THREAD

**Issue by muesli** [PixlOne/logiops#76]
Since a recent Arch update, every time I reboot my machine, vertical scrolling with the wheel is super slow. I have to stop `logid`, edit the config file and set `hires` to `false`, then restart `logid` again to fix it. However, after a while (sometimes an hour or more) suddenly my scrolling will become super fast. Now I have to go back to the config, change `hires` to `true` again to fix it.

I can't make any sense of it, hope you got an idea. Running latest Arch and latest logiops from git.

**Comment by PixlOne** [comment]
Is this only happening over Bluetooth? Linux 5.6 added support to some Bluetooth Logitech devices on hid-logitech-hidpp which means that scrolling now acts differently on those devices.

**Comment by muesli** [comment]
No, I'm exclusively using the proprietary Logitech receiver.

**Comment by zv0n** [comment]
I'm also experiencing some weird hi-res behavior. For me sometimes after I reboot, the scrolling is super fast. Turning the mouse off and on solves the problem (hooray for the oldest, most reliable solution to almost all problems! :D). If I had to guess, I'd say the mouse connects before logid properly starts, remembers that it's supposed to use hi-res, and when logid starts it adds another hi-res layer to that => super fast scrolling. This is purely a guess, I have no evidence to back it up, so feel free to disregard this.

**Comment by myralchista** [comment]
Is there a way to make hires scroll not so fast inside this program? I found solution for solaar, but not for this program:
https://rhtenhove.nl/blog/hires-scrolling-logitech/hires-scrolling-logitech/

**Comment by PixlOne** [comment]
@myralchista That's a udev rule so the same method should work with logid.

I'm also noticing the same issue occassionally although I don't quite know what triggers it. I'll try to investigate this further.

**Comment by vredez** [comment]
I'm facing the same issue with a MX Master 3.
Another (annoying) workaround is to replug the connector.

**Comment by vredez** [comment]
Update: I've found a better workaround that works for my needs, which is to completely remove the 'hires' section from the configuration file. Although a warning is shown regarding the missing section, the scrollwheel speed has been stable now for three days. This might give a hint where to track down the root cause of this issue.

**Comment by Qwerty-Space** [comment]
> I'm also experiencing some weird hi-res behavior. For me sometimes after I reboot, the scrolling is super fast. Turning the mouse off and on solves the problem (hooray for the oldest, most reliable solution to almost all problems! :D). If I had to guess, I'd say the mouse connects before logid properly starts, remembers that it's supposed to use hi-res, and when logid starts it adds another hi-res layer to that => super fast scrolling. This is purely a guess, I have no evidence to back it up, so feel free to disregard this.

Similar issue here, except my scrolling is SUPER slow regardless of whether I have hires on or off, after rebooting.

Turning the mouse of and of fixed it though.  Thank you

**Comment by muesli** [comment]
Fwiw, this issue has resolved itself here. Since it wasn't really reproducible I'm not sure if it was a logid or a kernel update. Closing this ticket hence.
