### ISSUE TITLE
Add option to generate default configuration file

### ISSUE THREAD

**Issue by comio** [PixlOne/logiops#8]
Hi,

Your project is interesting! I would like to configure my MX Master 3.
Can you add an option to logid in order to generate the default configuration skeleton? This should be useful for the first start.

Thanks a lot!

luigi

**Comment by PixlOne** [comment]
A default configuration skeleton is kind of unnecessary as the device already has a default config and the config files are not necessarily meant to be configured by the user directly

I've been busy for a while but when I have time I'll try to create a configuration utility that should automatically probe the device for its features and buttons,

In the meantime, you can use the `hidpp20-reprog-controls` and `hidpp-list-features` utilities in [my hidpp repository](https://github.com/PixlOne/hidpp) to identify the control IDs and features available on the device. I've also compiled [a list of CIDs I've identified](https://github.com/PixlOne/logiops/wiki/CIDs) on my wiki (which mostly consists of random documentation dumps as of now).
