### ISSUE TITLE
Press multiple Buttons nearly simultaneously

### ISSUE THREAD

**Issue by dennisdenk** [PixlOne/logiops#80]
On Ubuntu you can press Super + Page Down/Up to Move between workspaces. But I didnt find a way to press "Super" with the Mouse and therefore not to press super and page down simultaneosly, is there a way?

**Comment by PixlOne** [comment]
You can use `KEY_LEFTMETA` for the left super key code or `KEY_RIGHTMETA` for the right super key code.

**Comment by LordZero25** [comment]
The syntax for multiple keypress

`action =
							{
								type: "Keypress";
								keys: ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_UP"];
							};`

**Comment by dennisdenk** [comment]
Thanks! That solved the question.
